# Generated by Django 2.0.1 on 2018-01-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('defindex', models.IntegerField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=150, null=True)),
                ('image_url_large', models.CharField(max_length=150, null=True)),
                ('item_class', models.CharField(max_length=50, null=True)),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('item_quality', models.IntegerField(default=6)),
                ('item_slot', models.CharField(db_index=True, max_length=10, null=True)),
                ('per_class_loadout_slots', models.CharField(max_length=10, null=True)),
                ('proper_name', models.BooleanField(default=False)),
                ('used_by_classes', models.CharField(db_index=True, max_length=10)),
                ('nameable', models.BooleanField(db_index=True, default=False)),
                ('paintable', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_num', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('defindex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='schema.Item')),
                ('collectors', models.BooleanField(default=False)),
                ('community', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('customized', models.BooleanField(default=False)),
                ('genuine', models.BooleanField(default=False)),
                ('haunted', models.BooleanField(default=False)),
                ('normal', models.BooleanField(default=False)),
                ('rarity2', models.BooleanField(default=False)),
                ('rarity3', models.BooleanField(default=False)),
                ('self_made', models.BooleanField(default=False)),
                ('strange', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=True)),
                ('unusual', models.BooleanField(default=False)),
                ('valve', models.BooleanField(default=True)),
                ('vintage', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='style',
            name='defindex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Item'),
        ),
    ]
